# Generated by Django 5.1 on 2025-03-17 15:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutstreak',
            name='completed',
        ),
        migrations.AlterField(
            model_name='workoutstreak',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='workoutstreak',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutstreak',
            name='workout_type',
            field=models.CharField(max_length=100),
        ),
    ]
