# Generated by Django 5.1 on 2025-03-17 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_workoutstreak_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workoutstreak',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='workoutstreak',
            name='calories',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workoutstreak',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
