# Generated by Django 5.1 on 2025-02-16 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_gptinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gptinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='gptinfo',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
