# Generated by Django 5.1 on 2025-03-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_workoutstreak_options_workoutstreak_calories_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutstreak',
            name='user',
        ),
    ]
